import fs from "node:fs";
import path from "node:path";
import YAML from "yaml";
import { TestSpecSchema, type TestSpec } from "../grader/lib/test-spec.ts";
import type { Curation } from "./curation.ts";

export interface MaterializeMeta {
  /** Which model produced the prompt (for the YAML comment block). */
  generatorModel: string;
  /** Generator temperature used for this variant (for the YAML comment). */
  temperature: number;
  /** 1-based variant index among N variants generated. */
  variantIndex: number;
  variantCount: number;
}

export interface MaterializedTask {
  taskDir: string;
  relTaskName: string; // e.g. "generated/recon-summarize-what-s-in-dir-01"
  yamlPath: string;
}

/**
 * Build a TestSpec object from a curation + generated prompt. Runs it
 * through the Zod schema before returning so shape drift breaks loudly.
 */
export function buildTestSpec(curation: Curation, prompt: string): TestSpec {
  const obj =
    curation.kind === "gap"
      ? {
          skill: "pi-agent-assembler" as const,
          expectation: {
            kind: "gap" as const,
            ...(curation.closestMatch ? { closest_match: curation.closestMatch } : {}),
          },
          prompt,
        }
      : {
          skill: "pi-agent-assembler" as const,
          expectation: {
            kind: "assembly" as const,
            pattern: curation.pattern as string,
            ...(curation.extraTools?.length ? { extra_tools: curation.extraTools } : {}),
            ...(curation.extraComponents?.length
              ? { extra_components: curation.extraComponents }
              : {}),
          },
          prompt,
          ...(curation.probe
            ? {
                probe: {
                  args: curation.probe.args,
                  ...(curation.probe.evidence_anchor
                    ? { evidence_anchor: curation.probe.evidence_anchor }
                    : {}),
                },
              }
            : {}),
        };

  const result = TestSpecSchema.safeParse(obj);
  if (!result.success) {
    const issues = result.error.issues
      .map((i) => `  ${i.path.join(".") || "(root)"}: ${i.message}`)
      .join("\n");
    throw new Error(`Generated test.yaml failed schema validation for ${curation.tag}:\n${issues}`);
  }
  return result.data;
}

/**
 * Serialize a TestSpec to YAML with a leading comment block that
 * records provenance (curation + generator settings). Returns the
 * raw YAML string — the caller decides where to write it.
 */
export function serializeTestSpec(curation: Curation, spec: TestSpec, meta: MaterializeMeta): string {
  const header = [
    `# Auto-generated by scripts/reverse-pipeline — do not edit by hand.`,
    `# Curation: kind=${curation.kind} pattern=${curation.pattern} tag=${curation.tag}`,
    `# Seed: ${oneLine(curation.phrasingSeed)}`,
    `# Generator: model=${meta.generatorModel} temperature=${meta.temperature} variant=${meta.variantIndex}/${meta.variantCount}`,
    `# Regenerate: npm run reverse-pipeline -- --only ${curation.tag}`,
    "",
  ].join("\n");
  return header + YAML.stringify(spec, { lineWidth: 0 });
}

/**
 * Write a curation+prompt pair to
 * scripts/approach-b-framework/tasks/generated/<tag>/test.yaml.
 * Returns the paths used so the CLI can log them and invoke the runner.
 */
export function materialize(
  repoRoot: string,
  curation: Curation,
  prompt: string,
  meta: MaterializeMeta,
): MaterializedTask {
  const spec = buildTestSpec(curation, prompt);
  const yaml = serializeTestSpec(curation, spec, meta);
  const relTaskName = path.join("generated", curation.tag);
  const taskDir = path.join(
    repoRoot,
    "scripts",
    "approach-b-framework",
    "tasks",
    relTaskName,
  );
  const yamlPath = path.join(taskDir, "test.yaml");
  fs.mkdirSync(taskDir, { recursive: true });
  fs.writeFileSync(yamlPath, yaml);
  return { taskDir, relTaskName, yamlPath };
}

function oneLine(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}
